manicure/urls.py
from django.contrib import admin
from django.urls import path, include

from records.views import RecordAPIView, RecordUpdateAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('records.urls')),
    path('api/v1/recordlist/', RecordAPIView.as_view()),
    path('api/v1/recordlist/<int:pk>/', RecordUpdateAPIView.as_view()),
    path('api/v1/auth/', include('rest_framework.urls')),
]

records/urls.py
from django.urls import path, include
from .views import home, record_occupied, cansel_record, RecordView, RecordAddView, ShowRecordView, DeleteRecordView


app_name = 'records'
urlpatterns = [
    path('', home, name='home'),
    path('records/', RecordView.as_view(), name='records'),
    path('records/record_add', RecordAddView.as_view(), name='record_add'),
    path('records/show_record/<int:pk>/', ShowRecordView.as_view(), name='show_record'),
    path('records/record_occupied/<int:record_pk>/', record_occupied, name='record_occupied'),
    path('records/delete_record/<int:pk>/', DeleteRecordView.as_view(), name='delete_record'),
    path('records/cansel_record/<int:record_pk>/', cansel_record, name='cansel_record'),

]

users/urls.py
from django.urls import path, include
from .views import UserLoginView, UserLogoutView, RegisterUserView, ChangeUserInfoView, AdministrationView, profile

app_name = 'users'
urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/profile/<int:user_id>', profile, name='profile'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('account/profile/change/', ChangeUserInfoView.as_view(), name='change'),
    path('administration/', AdministrationView.as_view(), name='administration'),
    ]

records/models.py
from django.db import models
from users.models import User

class Record(models.Model):
    time = models.TimeField()
    date = models.DateField()
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    occupied = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    # def __str__(self):
    #     return self.user

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

records/forms.py
from .models import Record
from django import forms

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['time', 'date']
        labels = {'time': 'Время', 'date': 'Дата', 'occupied': 'Занято'}

records/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.detail import DetailView
from users.models import User
from .models import Record
from .forms import RecordForm
from .serializers import RecordSerializer, RecordOccupiedSerializer
from .tasks import record_created, record_canceled
from rest_framework import generics

class RecordView(ListView):
    model = Record
    template_name = 'records/records.html'
    context_object_name = 'records'

    def get_queryset(self):
        return Record.objects.filter(is_active=True).order_by('date', 'time')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['months'] = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                             'Октябрь', 'Ноябрь', 'Декабрь']
        context['days'] = ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье']
        return context

class RecordAllView(ListView):
    model = Record
    template_name = 'records/records_all.html'
    context_object_name = 'records'

    def get_queryset(self):
        return Record.objects.all()




class RecordAddView(CreateView):
    template_name = 'records/record_add.html'
    form_class = RecordForm
    success_url = reverse_lazy('records:records')

class ShowRecordView(DetailView):
    model = Record
    template_name = 'records/show_record.html'
    context_object_name = 'record'

class DeleteRecordView(DeleteView):
    model = Record
    template_name = 'records/delete_record.html'
    success_url = reverse_lazy('users:administration')

def home(request):
    return render(request, 'records/home.html')

''' запись становится занята текущем пользователем и отправка сообщения об успешной записи ему на почту '''
def record_occupied(request, record_pk):
    record = Record.objects.get(id=record_pk)

    if request.user.is_authenticated and not record.user:
        record.user = User.objects.get(id=request.user.id)
        record.occupied = True
        record.save()
        record_created.delay(record_id=record_pk, user_id=request.user.id)
        return redirect('records:records')

# отмена записи
def cansel_record(request, record_pk):
    record = Record.objects.get(id=record_pk)
    record.occupied = False
    record.user = None
    record.save()
    record_canceled(record_id=record_pk, user_id=request.user.id)
    return redirect('records:home')

class RecordAPIView(generics.ListAPIView):
    queryset = Record.objects.filter(is_active=True).order_by('date', 'time')
    serializer_class = RecordSerializer

class RecordUpdateAPIView(generics.UpdateAPIView):
    queryset = Record.objects.filter(is_active=True).order_by('date', 'time')
    serializer_class = RecordOccupiedSerializer

records/templates/records/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Маникюр Любовь{% endblock title %}</title>
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital@0;1&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="body">

<div class="header">
    <div class="container">
        <div class="header-block">
            <div class="logo">
                <img class="logo-img" src="{% static 'logo.jpg' %}" alt="">
            </div>
            <div class="nav">
                <a class="nav-item" href="{% url 'records:home' %}">Маникюр | К-510 | Любовь</a>
                {% if user.is_admin %}
                <a class="nav-item" href="{% url 'users:administration' %}">Администрирование</a>
                {% endif %}
            </div>
            {% if user.is_authenticated %}
            <div class='nav-user'>
                <a href="{% url 'users:profile' user.id %}">Профиль</a>
                <a href="{% url 'users:logout' %}">Выход</a>
            </div>
             {% else %}
            <div class='nav-user'>
                <a href="{% url 'users:register' %}">Регистрация</a>
                <a href="{% url 'users:login' %}">Вход</a>
            </div>
            {% endif %}
        </div>     
    </div>
</div>
{% block content %}

{% endblock content %}
</body>
</html>

records/templates/records/delete_record.html
{% extends "records/base2.html" %}

{% block content %}
Вы точно хотите удалить запись?
<p>Время: {{ record.time }} Дата: {{ record.date }}</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить запись">
</form>
{% endblock content %}

records/templates/records/home.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}
<div class="background-home">
<div class="block-record">
    <div class="container">
        <div class="about-me">
            <div class="about-me-left">
                <div class="about-me-left-title">
                    <h2>
                        Обо мне
                    </h2>
                </div>
                <div div class="about-me-left-text">
                    <p>Здравствуйте! Меня зовут Любовь, я мастер ногтевого сервиса с опытом работы более 6 лет. Обладаю знаниями правил и норм обработки маникюрного инструмента. Выполняю комбинированный маникюр, наращивание и укрепление ногтей. Имею опыт работы в топ-салонах. Жду Вас у себя!</p>
                </div>
            </div>
            <div class="about-me-right">
                <div class="my-photo-block">
                    <img class="my-photo" src="{% static 'my2.jpg' %}">
                </div>
                <div class="button">
                <a href="{% url 'records:records' %}">Записаться онлайн</a>
                </div>
            </div>
            
        </div>
    </div>
</div>

<div class="block-my-works">
    <div class="container">
        <div class="title-my-work">
            <h2>Мои работы</h2>
        </div>
        <div>
            <div class="line-photo-one">
                <div class="photo-card">
                    <img class="photo" src="{% static 'work1.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work2.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work9.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work3.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work4.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work5.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work6.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work7.jpg' %}">
                </div>
                <div class="photo-card">
                    <img class="photo" src="{% static 'work8.jpg' %}">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="block-price">
    <div class="container">
        <div class="price-list">
            <img class="price" src="{% static 'price.jpg' %}">
        </div>
    </div>
</div>

<div class="block-end">
    <div class="container-end">
        <div class="contact">
            <div class="phone-number">
                <div >
                    <img class="phone" src="{% static 'phone.webp' %}">
                </div>
                <div class="number">
                    <span>+7-(903)-833-93-20</span>
                </div>
            </div>
            <div class="mail-adress">
                <div >
                    <img class="mail" src="{% static 'mail.png' %}">
                </div>
                <div class="number">
                    <span>manicurelovet@gmail.com</span>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
{% endblock content %}

records/templates/records/record_add.html
{% extends "records/base2.html" %}

{% block content %}

<form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить новую запись">
</form>

{% endblock content %}

records/templates/records/records.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}


<div class="records">
	<div class="container">
		<div class="line-records">
			{% for record in records %}
			<div class="record">
				<div class="record-title">
					{% if record.date.month == 1 %}
					<span>Январь</span>
					{% elif record.date.month == 2 %}
					<span>Февраль</span>
					{% elif record.date.month == 3 %}
					<span>Март</span>
					{% elif record.date.month == 4 %}
					<span>Апрель</span>
					{% elif record.date.month == 5 %}
					<span>Май</span>
					{% elif record.date.month == 6 %}
					<span>Июнь</span>
					{% elif record.date.month == 7 %}
					<span>Июль</span>
					{% elif record.date.month == 8 %}
					<span>Август</span>
					{% elif record.date.month == 9 %}
					<span>Сентябрь</span>
					{% elif record.date.month == 10 %}
					<span>Октябрь</span>
					{% elif record.date.month == 11 %}
					<span>Ноябрь</span>
					{% elif record.date.month == 12 %}
					<span>Декабрь</span>
					{% endif %}
				</div>
				<div class="record-content">
					{% if record.date.weekday == 0 %}
					<span class="day-week">Понедельник</span>
					{% elif record.date.weekday == 1 %}
					<span class="day-week">Вторник</span>
					{% elif record.date.weekday == 2 %}
					<span class="day-week">Среда</span>
					{% elif record.date.weekday == 3 %}
					<span class="day-week">Четверг</span>
					{% elif record.date.weekday == 4 %}
					<span class="day-week">Пятница</span>
					{% elif record.date.weekday == 5 %}
					<span class="day-week">Суббота</span>
					{% elif record.date.weekday == 6 %}
					<span class="day-week">Воскресенье</span>
					{% endif %}
					<br>
					<span class="record-number">{{ record.date.day }}</span>
					<br>
					<span class="record-time">{{ record.time }}</span>
					{% if record.occupied == False %}
                    {% if user.is_authenticated %}
					<div class="record-button">
					    <a class="record-btn" href="{% url 'records:show_record' record.id %}">Записаться</a>
				    </div>
				    {% else %}
				    <div class="record-button">
					    <a class="record-btn" href="{% url 'users:login' %}">Записаться</a>
				    </div>
				    {% endif %}
				    {% else %}
				    <div class="record-button-occupied">
					    <span class="record-occupied">Занято</span>
				    </div>
                    {% endif %}
				</div>
			</div>
			{% empty %}
            <span class="record-not"> Запись временно недоступна!</span>
			{% endfor %}
		</div>
	</div>
</div>


{% endblock content %}

records/templates/records/show_record.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}



<div class="block-show-records">
    <div class="container">
        <div class="show-records">
            <div class="show-records-time">
                Время: {{ record.time }}
            </div>
            <div class="show-records-date">
                Дата: {{ record.date }}
            </div>
             <div>
                <form class="form-show-record" action="{% url 'records:record_occupied' record.pk %}" method="post">
                {% csrf_token %}
                <button class="btn-show-record" type="submit"><span>Подтвердить запись!</span></button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}