manicure/urls.py
from django.contrib import admin
from django.urls import path, include

from records.views import RecordAPIView, RecordUpdateAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('records.urls')),
    path('api/v1/recordlist/', RecordAPIView.as_view()),
    path('api/v1/recordlist/<int:pk>/', RecordUpdateAPIView.as_view()),
    path('api/v1/auth/', include('rest_framework.urls')),
]

records/urls.py
from django.urls import path, include
from .views import home, record_occupied, cansel_record, RecordView, RecordAddView, ShowRecordView, DeleteRecordView


app_name = 'records'
urlpatterns = [
    path('', home, name='home'),
    path('records/', RecordView.as_view(), name='records'),
    path('records/record_add', RecordAddView.as_view(), name='record_add'),
    path('records/show_record/<int:pk>/', ShowRecordView.as_view(), name='show_record'),
    path('records/record_occupied/<int:record_pk>/', record_occupied, name='record_occupied'),
    path('records/delete_record/<int:pk>/', DeleteRecordView.as_view(), name='delete_record'),
    path('records/cansel_record/<int:record_pk>/', cansel_record, name='cansel_record'),

]

users/urls.py
from django.urls import path, include
from .views import UserLoginView, UserLogoutView, RegisterUserView, ChangeUserInfoView, AdministrationView, profile

app_name = 'users'
urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/profile/<int:user_id>', profile, name='profile'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('account/profile/change/', ChangeUserInfoView.as_view(), name='change'),
    path('administration/', AdministrationView.as_view(), name='administration'),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.validators import RegexValidator

class UserAccountManager(UserManager):

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        extra_fields['telephone_number'] = '00000000000'
        extra_fields['birth_date'] = '1999-01-01'

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(username, email, password, **extra_fields)

class User(AbstractUser):
    objects = UserAccountManager()
    telephone_number_regex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    telephone_number = models.CharField(
        validators=[telephone_number_regex],
        max_length=16,
        unique=True,
        null=True,
        blank=True,
        verbose_name="Номер телефона"
    )
    birth_date = models.DateField(verbose_name="Дата рождения")
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from .models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    email = forms.EmailField(max_length=250, label='Адрес электронной почты')
    first_name = forms.CharField(max_length=250, label='Имя')
    last_name = forms.CharField(max_length=250, label='Фамилия')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'birth_date', 'telephone_number']
        labels = {'username': 'Имя пользователя'}

class ChangeUserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'birth_date', 'telephone_number']

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView

from .models import User
from .forms import UserForm, ChangeUserInfoForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from records.models import Record

class UserLoginView(LoginView):
    template_name = 'users/login.html'
    success_url = reverse_lazy('records/home.html')

@login_required
def profile(request, user_id):
    records = Record.objects.filter(user=user_id, is_active=True)
    context = {'records': records}
    return render(request, 'users/profile.html', context)

class UserLogoutView(LogoutView, LoginRequiredMixin):
    template_name = 'users/logout.html'

class RegisterUserView(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = UserForm
    success_url = reverse_lazy('records:home')

class ChangeUserInfoView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    model = User
    template_name = 'users/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('records:home')
    success_message = 'Данные пользователя успешно изменены!'

    def setup(self, request, *args, **kwargs):     # выполняется самым первым и инициализирует объект контроллера
        self.user_id = request.user.pk             # переопределяя сохраняем первичный ключ юзера
        return super().setup(request, *args, **kwargs)
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class AdministrationView(ListView):
    model = User
    template_name = 'users/administration.html'
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['records'] = Record.objects.all()
        return context

users/templates/users/administration.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}
Действующие записи
{% for record in records %}
<p> Время: {{ record.time }} Дата: {{ record.date }} ID:{{ record.id }} </p>
<a href="{% url 'records:delete_record' record.id %}">Удалить запись</a>
{% endfor %}
<li class="nav-item">
    <a href="{% url 'records:record_add' %}">
        Добавить новую запись
    </a>
</li>
База данных пользователей
{% for user in users %}
<p>
    <a href="{% url 'users:profile' user.id %}">{{ user.username }}</a> - {{ user.first_name }} {{ user.last_name }} Номер телефона: {{ user.telephone_number}}
    Дата регистрации: {{ user.date_joined}} Последний вход: {{ user.last_login}}
</p>
{% endfor %}

{% endblock content %}

users/templates/users/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Маникюр_Люба</title>


</head>
<body>
<nav class="navbar navbar-expand-md navbar-ligth bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'records:home' %}">
        Дом
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'records:records' %}">
                    Записи
                </a>
            </li>
            {% if user.is_admin %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:administration' %}">
                    Администрирование
                </a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text"}>Здравствуйте, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' user.id %}">Профиль</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>
</body>
</html>

users/templates/users/change_user_info.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}


<div class="block-change-user-info">
    <div class="container-register">
        <div class=block-change-user-info-title">
            <h2>Изменение личных данных</h2>
        </div>
        <div>
            <form class="form-register" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="btn-show-record" type="submit"><span>Сохранить изменения</span></button>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

users/templates/users/login.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}

<div class="block-login">
    <div class="container">
        <div class="block-login-tittle">
            <h2>Вход</h2>
        </div>
        <div class="show-records">
            {% if user.is_authenticated %}
            <h2>Вы уже выполнили вход!</h2>
            {% else %}
            <form class="form-login" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="hidden" name="next" value="{{ next }}">
            <button class="btn-show-record" type="submit"><span>Войти</span></button>
            </form>
            {% endif %}
        </div>
    </div>
</div>




{% endblock content %}

users/templates/users/logout.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}
<div class="block-login-tittle">
	<h2>Выход</h2>
</div>
<div class="title-my-work">
	<span>Вы успешно вышли с сайта!</span>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}



<div class="block-profile">
	<div class="container">
		<div class="profile">
			<div class="block-login-tittle">
				<h2>Ваш профиль</h2>
			</div>
			<div class="info-flex">
				<div class="info-block">
					<div class="title-info">
						<h3>Личная информация</h3>
					</div>
					<div class="info">
						<p class="info-p">Имя: {{ user.first_name }}</p>
						<p class="info-p">Фамилия: {{ user.last_name }}</p>
						<p class="info-p">Никнейм: {{ user.username }}</p>
						<p class="info-p">Почта: {{ user.email }}</p>
						<p class="info-p">Номер телефона: {{ user.telephone_number }}</p>
						<p class="info-p">День рождения: {{ user.birth_date }}</p>
					</div>
					<div class="change-info-block">
						<a class="change-info" href="{% url 'users:change' %}">Изменить личные данные</a>
					</div>
				</div>
				<div class="block-my-record">
					<div class="title-info">
						<h3>Мои записи</h3>
					</div>
					<div class="my-records">
						{% for record in records %}
						<div class="my-record">
							<p class="info-p"> Дата: {{ record.date }}</p>
							<p class="info-p"> Время: {{ record.time }}</p>
							<div>
								<a class="change-info" href="{% url 'records:cansel_record' record.pk %}">Отменить запись</a>
							</div>
						</div>
						{% empty %}
						<div class="title-info">
						    <h3>Записей пока нет!</h3>
					    </div>
						{% endfor %}
					</div>

				</div>
			</div>
{% endblock content %}

users/templates/users/register.html
{% extends "records/base2.html" %}
{% load static %}
{% block content %}


<div class="block-login">
    <div class="container-register">
        <div class="block-login-tittle">
            <h2>Регистрация</h2>
        </div>
        <div>
            <form class="form-register" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="hidden" name="next" value="{{ next }}">
            <button class="btn-show-record" type="submit"><span>Зарегистрироваться</span></button>
            </form>
        </div>
    </div>
</div>



{% endblock content %}